INSERT INTO U_UploadPurchaseReceiptData
        (
            BatchNo,
            InvoiceNo,
            InvoiceDate,
            PONo,
            [LineNo],
            ItemCode,
            Quantity,
            UnitPrice,
            ClientAddress,
            UserCreated,
            DateCreated,
            StatusFlag
        )
        VALUES
        (
            @BatchNo,
            @InvoiceNo,
            @InvoiceDate,
            @PONo,
            @LineNo,
            @ItemCode,
            @Quantity,
            @UnitPrice,
            @ClientAddress,
            @UserCreated,
            @DateCreated,
            '0'
        );